spring:
  devtools:
    livereload:
      enabled: true

# loggin.file , logging.file.maxHistory
# https://github.com/spring-projects/spring-boot/issues/12510
logging.file: /data/log/observer/obersver.log
logging:
  level:
    root: info
  file:
    max-history: 7

git:
  myID: nokchax
  token: personal access token from git(https://github.com/settings/tokens)
  api:
    search:
      commentUrl: https://api.github.com/search/commits
      commentQuery: ?q=committer:%s+committer-date:%s..%s+sort:committer-date-desc+is:public

slack:
  webhook:
    urlOfMine: u can get url from Incoming WebHooks slack app
  bot:
    token:
naver:
  oauth:
    clientId:
    clientSecret:
  apiUrl: https://openapi.naver.com/v1/papago/n2mt
