spring:
  devtools:
    livereload:
      enabled: true

logging:
  level:
    root: info
  file: /data/log/observer/obersver.log
    maxhistory: 7

git:
  myID: nokchax
  token: personal access token from git(https://github.com/settings/tokens)
  api:
    search:
      commentUrl: https://api.github.com/search/commits
      commentQuery: ?q=committer:%s+committer-date:%s..%s+sort:committer-date-desc

slack:
  webhook:
    urlOfMine: u can get url from Incoming WebHooks slack app
