spring:
  devtools:
    livereload:
      enabled: true

git:
  token: personal access token from git(https://github.com/settings/tokens)
  api:
    search:
      commentUrl: https://api.github.com/search/commits
      commentQuery: ?q=committer:%s+committer-date:>=%s+sort:committer-date-desc
